// Missoes 2º Semestre/Missão Prática - Nível 4/livros-angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'livros-angular';
}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <a class="navbar-brand" routerLink="/lista">Livros</a>
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" routerLink="/lista">Lista</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" routerLink="/dados">Dados</a>
      </li>
    </ul>
  </div>
</nav>

<router-outlet></router-outlet>

// Missoes 2º Semestre/Missão Prática - Nível 3/livros-react/src/App.tsx
import React from 'react';
import { BrowserRouter, Link, Routes, Route } from 'react-router-dom';
import LivroLista from "./LivroLista"
import LivroDados from "./LivroDados"

function App() {
  return (
    <BrowserRouter>
      <nav className="navbar navbar-expand-lg navbar-light bg-light">
        <div className="container-fluid">
          <Link className="navbar-brand" to="/">Livros React</Link>
          <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span className="navbar-toggler-icon"></span>
          </button>
          <div className="collapse navbar-collapse" id="navbarNav">
            <ul className="navbar-nav">
              <li className="nav-item">
                <Link className="nav-link" to="/">Lista</Link>
              </li>
              <li className="nav-item">
                <Link className="nav-link" to="/dados">Dados</Link>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      <Routes>
        <Route path="/" element={<LivroLista />} />
        <Route path="/dados" element={<LivroDados />} />
      </Routes>
    </BrowserRouter>
  );
}

export default App;
