// Missoes 2º Semestre/Missão Prática - Nível 4/livros-angular/src/app/livro-lista/livro-lista.component.ts
import { Component, OnInit } from '@angular/core';
import { Editora } from '../editora';
import { Livro } from '../livro';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';

@Component({
  selector: 'app-livro-lista',
  template: `
    <h2>Editoras:</h2>
    <ul>
      <li *ngFor="let editora of editoras">{{ editora.nome }}</li>
    </ul>
    <h2>Livros:</h2>
    <table class="table">
      <thead>
        <tr>
          <th>Código</th>
          <th>Título</th>
          <th>Resumo</th>
          <th>Autores</th>
          <th>Editora</th>
          <th>Ações</th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let livro of livros">
          <td>{{ livro.codigo }}</td>
          <td>{{ livro.titulo }}</td>
          <td>{{ livro.resumo }}</td>
          <td>{{ livro.autores.join(', ') }}</td>
          <td>{{ obterNome(livro.codEditora) }}</td>
          <td>
            <button class="btn btn-danger" (click)="excluir(livro.codigo)">Excluir</button>
          </td>
        </tr>
      </tbody>
    </table>
  `
})
export class LivroListaComponent implements OnInit {
  editoras: Array<Editora> = [];
  livros: Array<Livro> = [];

  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService
  ) {}

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
    this.livros = this.servLivros.obterLivros();
  }

  excluir(codigo: number): void {
    this.servLivros.excluir(codigo);
    this.livros = this.servLivros.obterLivros();
  }

  obterNome(codEditora: number): string {
    return this.servEditora.getNomeEditora(codEditora);
  }
}

<main class="container">
    <h1>Livros</h1>
    <table class="table">
      <thead>
        <tr>
          <th>Código</th>
          <th>Título</th>
          <th>Resumo</th>
          <th>Autores</th>
          <th>Editora</th>
          <th>Ações</th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let livro of livros">
          <td>{{ livro.codigo }}</td>
          <td>{{ livro.titulo }}</td>
          <td>{{ livro.resumo }}</td>
          <td>
            <ul>
              <li *ngFor="let autor of livro.autores">{{ autor }}</li>
            </ul>
          </td>
          <td>{{ obterNome(livro.codEditora) }}</td>
          <td>
            <button class="btn btn-danger" (click)="excluir(livro.codigo)">Excluir</button>
          </td>
        </tr>
      </tbody>
    </table>
  </main>

// Missoes 2º Semestre/Missão Prática - Nível 3/livros-react/src/LivroLista.js
import React, { useState, useEffect } from "react";
import { ControleLivros } from "../controle/ControleLivros";
import { ControleEditora } from "../controle/ControleEditora";
import { Livro } from "../modelo/Livro";

export const LivroLista: React.FC = () => {
  const [livros, setLivros] = useState<Livro[]>([]);
  const controleLivro = new ControleLivros();
  const controleEditora = new ControleEditora();

  useEffect(() => {
    setLivros(controleLivro.obterLivros());
  }, []);

  return (
    <div>
      <h1>Livros</h1>
      <table className="table">
        <thead>
          <tr>
            <th>Código</th>
            <th>Título</th>
            <th>Editora</th>
            <th>Autores</th>
            <th>Ações</th>
          </tr>
        </thead>
        <tbody>
          {livros.map((livro) => (
            <tr key={livro.codigo}>
              <td>{livro.codigo}</td>
              <td>{livro.titulo}</td>
              <td>{controleEditora.getNomeEditora(livro.codEditora)}</td>
              <td>{livro.autores.join(", ")}</td>
              <td>
                <button
                  className="btn btn-danger"
                  onClick={() => {
                    controleLivro.excluir(livro.codigo);
                    setLivros(controleLivro.obterLivros());
                  }}
                >
                  Excluir
                </button>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
};
